### ISSUE TITLE
#11 fails to compile in linux

### ISSUE THREAD

**Issue by fedex81** [danibusvlc/aventuras-en-megadrive#1]
Hello,
first of all great stuff, really interesting examples ;)

Getting an error when compiling in linux using gendev.
`
/opt/gendev/bin/m68k-elf-gcc -B/opt/gendev/sgdk/bin -n -T /opt/gendev/sgdk/md.ld -nostdlib out/sega.o @out/cmd_ /opt/gendev/sgdk/lib/libmd.a /opt/gendev/sgdk/lib/libgcc.a -o out/rom.out
/opt/gendev/sgdk/lib/libmd.a(sys_a.o): In function SYS_hardReset:
(.text+0x1c): undefined reference to _hard_reset
collect2: error: ld returned 1 exit status
make: *** [/opt/gendev/sgdk/mkfiles/makefile.gen:122: out/rom.out] Error 1
`
When I replace sega.s with the one used in lesson 10, everything works.

**Comment by danibusvlc** [comment]
Sorry but not using linux now, check with Stef, SGDK creator.

**Comment by fedex81** [comment]
No worries, I assumed that #11 would be broken in win too, but it could just be an issue with the linux toolchain.
